export const KlasemenData = [
    {
        id: 1,
        No: 1,
        Klub : 'LEV',
        image: require('./src/assets/img/BayernLeverkusen.png'),
        Match: 9,
        Win: 8,
        Draw: 1,
        Lose: 0,
        Point: 25,
    },
    {
        id: 2,
        No: 2,
        Klub : 'BAY',
        image: require('./src/assets/img/BayernMunchen.png'),
        Match: 9,
        Win: 7,
        Draw: 2,
        Lose: 0,
        Point: 23,
    },
    {
        id: 3,
        No: 3,
        Klub : 'STU',
        image: require('./src/assets/img/VfBStuffgart.png'),
        Match: 9,
        Win: 7,
        Draw: 0,
        Lose: 2,
        Point: 21,
    },
    {
        id: 4,
        No: 4,
        Klub : 'DOR',
        image: require('./src/assets/img/BorussiaDortmund.png'),
        Match: 9,
        Win: 6,
        Draw: 2,
        Lose: 1,
        Point: 20,
    },
    {
        id: 5,
        No: 5,
        Klub : 'RBL',
        image: require('./src/assets/img/RBleipzig.png'),
        Match: 9,
        Win: 6,
        Draw: 2,
        Lose: 1,
        Point: 20,
    },
    {
        id: 6,
        No: 6,
        Klub : 'HOF',
        image: require('./src/assets/img/Hoffenheim.png'),
        Match: 9,
        Win: 6,
        Draw: 0,
        Lose: 3,
        Point: 18,
    },
    {
        id: 7,
        No: 7,
        Klub : 'FRA',
        image: require('./src/assets/img/EintrachtFrankfurt.png'),
        Match: 9,
        Win: 3,
        Draw: 5,
        Lose: 1,
        Point: 14,
    },
    {
        id: 8,
        No: 8,
        Klub : 'SCF',
        image: require('./src/assets/img/Freiburg.png'),
        Match: 9,
        Win: 4,
        Draw: 1,
        Lose: 4,
        Point: 13,
    },
    {
        id: 9,
        No: 9,
        Klub : 'WOB',
        image: require('./src/assets/img/Wolfsburg.png'),
        Match: 9,
        Win: 4,
        Draw: 0,
        Lose: 5,
        Point: 12,
    },
    {
        id: 10,
        No: 10,
        Klub : 'AUG',
        image: require('./src/assets/img/Augsburg.png'),
        Match: 9,
        Win: 3,
        Draw: 2,
        Lose: 4,
        Point: 11,
    },
    {
        id: 11,
        No: 11,
        Klub : 'BMG',
        image: require('./src/assets/img/mgladbach1.png'),
        Match: 9,
        Win: 2,
        Draw: 3,
        Lose: 4,
        Point: 9,
    },
    {
        id: 12,
        No: 12,
        Klub : 'BRE',
        image: require('./src/assets/img/bremen.png'),
        Match: 9,
        Win: 3,
        Draw: 0,
        Lose: 6,
        Point: 9,
    },
    {
        id: 13,
        No: 13,
        Klub : 'HEI',
        image: require('./src/assets/img/heldeinheim.png'),
        Match: 9,
        Win: 2,
        Draw: 1,
        Lose: 6,
        Point: 7,
    },
    {
        id: 14,
        No: 14,
        Klub : 'D98',
        image: require('./src/assets/img/darmstadt98.png'),
        Match: 9,
        Win: 2,
        Draw: 1,
        Lose: 6,
        Point: 7,
    },
    {
        id: 15,
        No: 15,
        Klub : 'UNI',
        image: require('./src/assets/img/unionberlin.png'),
        Match: 9,
        Win: 2,
        Draw: 0,
        Lose: 7,
        Point: 6,
    },
    {
        id: 16,
        No: 16,
        Klub : 'BOC',
        image: require('./src/assets/img/bochum.png'),
        Match: 9,
        Win: 0,
        Draw: 5,
        Lose: 4,
        Point: 5,
    },
    {
        id: 17,
        No: 17,
        Klub : 'KOE',
        image: require('./src/assets/img/FCKoln.png'),
        Match: 9,
        Win: 1,
        Draw: 1,
        Lose: 7,
        Point: 4,
    },
    {
        id: 18,
        No: 18,
        Klub : 'MAI',
        image: require('./src/assets/img/mainz05.png'),
        Match: 9,
        Win: 0,
        Draw: 3,
        Lose: 6,
        Point: 3,
    },
  ];

export const TopScoresData = [{
        id: 1,
        Nama: 'Serhou Guraissy',
        Klub : 'STU',
        Goal: 14,
    },
    {
        id: 2,
        Nama: 'Harry Kane',
        Klub : 'BAY',
        Goal: 12,
    },
    {
        id: 3,
        Nama: 'Leroy Sane',
        Klub : 'BAY',
        Goal: 8,
    },
    {
        id: 4,
        Nama: 'Loïs Openda',
        Klub : 'RBL',
        Goal: 8,
    },
    {
        id: 5,
        Nama: 'Jonas Wind',
        Klub : 'WOB',
        Goal: 8,
    },
    {
        id: 6,
        Nama: 'Victor Boniface',
        Klub : 'LEV',
        Goal: 7,
    },
    {
        id: 7,
        Nama: 'Maximilian Demitrovic',
        Klub : 'HOF',
        Goal: 6,
    },
    {
        id: 8,
        Nama: 'Jonas Hofmann',
        Klub : 'LEV',
        Goal: 5,
    },
    {
        id: 9,
        Nama: 'Eren Dinkci',
        Klub : 'HEI',
        Goal: 5,
    },
    {
        id: 10,
        Nama: 'Ermedin Demirović',
        Klub : 'AUF',
        Goal: 5,
    },
];

export const TopAssistData = [{
        id: 1,
        Nama : 'Xavi Simon',
        Klub : 'RBL',
        Assist : 7,
    },
    {
        id: 2,
        Nama : 'Leroy Sane',
        Klub : 'BAY',
        Assist : 6,
    },
    {
        id : 3,
        Nama : 'Victor Boniface',
        Klub : 'LEV',
        Assist : 5,
    },
    {
        id : 4,
        Nama : 'Jeremy Frimpong',
        Klub : 'LEV',
        Assist : 5,
    },
    {
        id : 5,
        Nama : 'Chris Führich',
        Klub : 'STU',
        Assist : 5,
    },
    {
        id : 6,
        Nama : 'Vincenzo Grifo',
        Klub : 'SCF',
        Assist : 5,
    },
    {
        id : 7,
        Nama : 'Jonas Hofmann',
        Klub : 'LEV',
        Assist : 5,
    },
    {
        id : 8,
        Nama : 'Harry Kane',
        Klub : 'BAY',
        Assist : 5,
    },
    {
        id : 9,
        Nama : 'Florian Wirtz',
        Klub : 'LEV',
        Assist : 5,
    },
    {
        id : 10,
        Nama : 'Thomas Müller',
        Klub : 'BAY',
        Assist : 4,
    },
]