export const KlasemenData = [
    {
        id: 1,
        No: 1,
        Klub : 'LEV',
        Match: 9,
        Win: 8,
        Draw: 1,
        Lose: 0,
        Point: 25,
    },
    {
        id: 2,
        No: 2,
        Klub : 'BAY',
        Match: 9,
        Win: 7,
        Draw: 2,
        Lose: 0,
        Point: 23,
    },
    {
        id: 3,
        No: 3,
        Klub : 'STU',
        Match: 9,
        Win: 7,
        Draw: 0,
        Lose: 2,
        Point: 21,
    },
    {
        id: 4,
        No: 4,
        Klub : 'DOR',
        Match: 9,
        Win: 6,
        Draw: 2,
        Lose: 1,
        Point: 20,
    },
    {
        id: 5,
        No: 5,
        Klub : 'RBL',
        Match: 9,
        Win: 6,
        Draw: 2,
        Lose: 1,
        Point: 20,
    },
    {
        id: 6,
        No: 6,
        Klub : 'HOF',
        Match: 9,
        Win: 6,
        Draw: 0,
        Lose: 3,
        Point: 18,
    },
    {
        id: 7,
        No: 7,
        Klub : 'FRA',
        Match: 9,
        Win: 3,
        Draw: 5,
        Lose: 1,
        Point: 14,
    },
    {
        id: 8,
        No: 8,
        Klub : 'SCF',
        Match: 9,
        Win: 4,
        Draw: 1,
        Lose: 4,
        Point: 13,
    },
    {
        id: 9,
        No: 9,
        Klub : 'WOB',
        Match: 9,
        Win: 4,
        Draw: 0,
        Lose: 5,
        Point: 12,
    },
    {
        id: 10,
        No: 10,
        Klub : 'AUG',
        Match: 9,
        Win: 3,
        Draw: 2,
        Lose: 4,
        Point: 11,
    },
    {
        id: 11,
        No: 11,
        Klub : 'BMG',
        Match: 9,
        Win: 2,
        Draw: 3,
        Lose: 4,
        Point: 9,
    },
    {
        id: 12,
        No: 12,
        Klub : 'BRE',
        Match: 9,
        Win: 3,
        Draw: 0,
        Lose: 6,
        Point: 9,
    },
    {
        id: 13,
        No: 13,
        Klub : 'HEI',
        Match: 9,
        Win: 2,
        Draw: 1,
        Lose: 6,
        Point: 7,
    },
    {
        id: 14,
        No: 14,
        Klub : 'D98',
        Match: 9,
        Win: 2,
        Draw: 1,
        Lose: 6,
        Point: 7,
    },
    {
        id: 15,
        No: 15,
        Klub : 'UNI',
        Match: 9,
        Win: 2,
        Draw: 0,
        Lose: 7,
        Point: 6,
    },
    {
        id: 16,
        No: 16,
        Klub : 'BOC',
        Match: 9,
        Win: 0,
        Draw: 5,
        Lose: 4,
        Point: 5,
    },
    {
        id: 17,
        No: 17,
        Klub : 'KOE',
        Match: 9,
        Win: 1,
        Draw: 1,
        Lose: 7,
        Point: 4,
    },
    {
        id: 18,
        No: 18,
        Klub : 'MAI',
        Match: 9,
        Win: 0,
        Draw: 3,
        Lose: 6,
        Point: 3,
    },
  ];